name: flutter_evil_vikings
description: A showcase of Forge2D + Flame for the Flutter Vikings conference

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame:
    git:
      url: https://github.com/flame-engine/flame.git
      ref: spydon.unify-removal

  flame_forge2d:
    git:
      url: https://github.com/flame-engine/flame_forge2d.git
      ref: spydon.simplify-rendering

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
